Nprp 19 модалка с добавлением расхода дохода
yudakov1814/FamilyBudget pull request #12
Opened 2022-01-10 16:51 UTC by e543

2022-01-10 16:54 UTC, e543 commented on FamilyBudget/Controllers/ModalController.cs
> +            addIncome.ProjectMemberId = _context.ProjectMembers.FirstOrDefault().Id; //??
БД не позволяет создать фин. операции без этих аттрибутов, поставил значения первых в списке как затычки.

2022-01-10 17:57 UTC, yudakov1814 requested changes

2022-01-10 17:57 UTC, yudakov1814 commented on FamilyBudget/Controllers/HomeController.cs
> +                    Category = project.Categories.Find(c => c.Name == "продукты"),
Сломал OverwriteDB, в FamilyBudget\CRUD models\CRUD_project.cs "Продукты" и прочее с большой буквы.
Проверить можно перейдя по ссылке https://localhost:44370/home/OverwriteDB (Порт (44370) может отличаться у нас с тобой). Метод OverwriteDB перезапишет базу данных и создаст юзера demo@mail.ru с паролем 123456

2022-01-10 17:57 UTC, yudakov1814 commented on FamilyBudget/Controllers/CategoriesController.cs
>                  return BadRequest();
Давай сюда хотя бы return BadRequest(ex.Message) напишем

2022-01-10 17:57 UTC, yudakov1814 commented on FamilyBudget/Controllers/CategoriesController.cs
> +                return BadRequest();
И сюда бы return BadRequest(ex.Message)

2022-01-10 17:57 UTC, yudakov1814 commented on FamilyBudget/Controllers/ModalController.cs
> +            addIncome.ProjectMemberId = _context.ProjectMembers.FirstOrDefault().Id; //??
Норм, пофиг на это

2022-01-10 17:57 UTC, yudakov1814 commented on FamilyBudget/Views/Modal/AddCharge.cshtml
> +                    </label>
Давай вот это уберем. Вместо галочки добавим фейкового члена семьи, назовем его "Семья". Пусть этот фейковый член семьи будет по дефолту в выпадающем списке. При этом в базе данных мы его не храним. Создаем в момент когда получаем членов семьи, делаем ему id = -1. Потом, когда пользователь нажал на кнопку сохранить, на бекенде смотрим id члена семьи. Если id==-1 то ставим ForAll = true (иначе false), а в ProjectMemberId пишем Null. Далее, когда мы отображаем расходы, мы должны смотреть на эту галку, если она стоит, то мы выводим "Семья". Тоже самое нужно сделать для доходов. То есть добавляем выпадающий список с членами семьи для доходов. Отображаем их потом также

2022-01-11 05:36 UTC, yudakov1814 requested changes

2022-01-11 05:36 UTC, yudakov1814 commented on FamilyBudget/Views/Home/Details.cshtml
> +                    <td class="col-3">@if (fo.ProjectMember != null) { <label>@fo.ProjectMember.NameInProject</label> }</td>
Вот здесь мы проверяем ProjectMember != null, давай иначе "Семья" писать

2022-01-11 05:36 UTC, yudakov1814 commented on FamilyBudget/Views/Modal/AddCharge.cshtml
> +                </div>
Давай тоже самое для доходов сделаем

2022-01-11 13:12 UTC, merged