Добавлены модальные окна для удаления проектов
yudakov1814/FamilyBudget pull request #9
Opened 2021-12-16 12:50 UTC by e543

2021-12-16 13:18 UTC, yudakov1814 requested changes

2021-12-16 13:18 UTC, yudakov1814 commented on FamilyBudget.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "FamilyBudget", "FamilyBudget\FamilyBudget.csproj", "{1B719B72-62BA-49A3-AEF6-F45479658AF7}"
А это зачем?

2021-12-16 13:18 UTC, yudakov1814 commented on FamilyBudget/Controllers/HomeController.cs
> +        public IActionResult Modal(int? id)
Лучше давай ModalController создадим и туда будем все модалки складывать. Название тоже лучше понимать, что-то вроде ProjectDeleteModal нужно. Потом еще Create будет Денис делать

2021-12-16 13:18 UTC, yudakov1814 commented on FamilyBudget/Views/Home/Index.cshtml
> +
Здесь тоже лучше название для Id более удачные подобрать, т.к. на странице не одна модалка будет

2021-12-16 13:18 UTC, yudakov1814 commented on FamilyBudget/Views/Home/Index.cshtml
> +                    </svg>
svg не топ, лучше <i class="bi bi-x-lg"></i> использовать.
Нужно в FamilyBudget\Views\Shared\_Layout.cshtml подключить иконки:
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
Тогда заработает

2021-12-16 13:18 UTC, yudakov1814 commented on FamilyBudget/Views/Home/Index.cshtml
> +               class="p-2 flex-grow list-group-item-action">
list-group-item-action лучше на div повесить, а то выделение при наведении не оч. красиво сморится

2021-12-16 13:18 UTC, yudakov1814 commented on FamilyBudget/Views/Home/Index.cshtml
> +            <a asp-action="Modal" asp-route-id="@item.Id" class="p-2 ml-3 projectItem">
Здесь тоже самое по названию, модалка не одна будет

2021-12-16 13:18 UTC, yudakov1814 commented on FamilyBudget/Views/Home/Modal.cshtml
> +        <p class="modal-title" id="deleteModalLabel">Are you sure you want to delete @Html.DisplayFor(model => model.Name)?</p>
Скучно выглядит. Давай что-нибудь поинтересней сделаем.
Можно добавить инфу, вроде кол-во расходов/доходов в этом проекте. Автор проекта. Дата создания. Дата последнего обновления. Кол-во членов семьи. Написать, что все это будет удалено.

2021-12-16 13:18 UTC, yudakov1814 commented on FamilyBudget/Views/Home/Modal.cshtml
> +        <p class="modal-title" id="deleteModalLabel">Are you sure you want to delete @Html.DisplayFor(model => model.Name)?</p>
Можно в details подглядеть как такой список полей сделать.

2021-12-16 17:09 UTC, e543 commented
Пока без доп инфы в модалке

2021-12-18 12:45 UTC, yudakov1814 requested changes

2021-12-18 12:45 UTC, yudakov1814 commented on FamilyBudget/Controllers/ModalController.cs
> +            ViewBag.chargesCount = project.FinOperations.Where(fo => fo.FinType == FinType.Charge).Count();
ViewBag не очень хорошая практика. Давай лучше создадим в корне проекта папку ModalViewModels. Там ну нас будет ProjectDeleteModel. В это методе на основе project будем заполнять ProjectDeleteModel, далее использовать полученную ProjectDeleteModel в PartialView

2021-12-18 12:45 UTC, yudakov1814 commented on FamilyBudget/Controllers/ModalController.cs
> +            }
В ajax такое лучше не делать. Для пользователя это будет не кликабельный крестик. Он будет на него тыкать и у него ничего не будет происходить. Куда копать - не понятно. Давай лучше в новой моделе ProjectDeleteModel (про нее ниже) добавим поле IsValid. Далее во view будем смотреть на это поле, если модель валидная, то отображаем как обычно, если что-то не так, то показываем модалку с ошибкой, это лучше, чем просто промолчать. Также можно добавить еще поля, вроде IsNotFound и IsForbid, тогда можно более информативный ответ для пользователя показывать.

2021-12-18 12:45 UTC, yudakov1814 commented on FamilyBudget/Views/Home/Index.cshtml
> +        </div>
div получается не кликабельный. Я навожу мышку на край, он начинает подсвечиваться, я тыкаю, происходит анимация, но по сути я нажал на div, а не на ссылку, из-за этого ничего не происходит.

Готовый кусок кода: https://pastebin.com/TxhEW4pw

И еще раз про то как подключить иконки:
1. Идешь в файл Views\Shared\_Layout.cshtml
2. После строки `<title>@ViewData["Title"] - FamilyBudget</title>` добавляешь строку `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">`
3. Профит

2021-12-18 12:45 UTC, yudakov1814 commented on FamilyBudget/wwwroot/lib/bootstrap/dist/icons/x-lg.svg
> +</svg>
Когда подключить иконки через `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">` это все убрать можно

2021-12-19 00:34 UTC, e543 commented on FamilyBudget/Controllers/ModalController.cs
Не решил куда лучше положить. Оставил здесь)

2021-12-19 00:35 UTC, e543 commented on FamilyBudget/Controllers/ModalController.cs
> +            projectDelete.chargesCount      = project.FinOperations.Where(fo => fo.FinType == FinType.Charge).Count();
Не решил куда лучше положить. Оставил здесь)

2021-12-19 00:43 UTC, e543 commented on FamilyBudget.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "FamilyBudget", "FamilyBudget\FamilyBudget.csproj", "{1B719B72-62BA-49A3-AEF6-F45479658AF7}"
подкинули отвечаю

2021-12-19 13:04 UTC, merged